### ISSUE TITLE
Change dynamic formatting sp_DBPermissions

### ISSUE THREAD

**Issue by sqlstudent144** [sqlstudent144/SQL-Server-Scripts#10]
I think it will be easier to read if I remove the + char... at the end of each line and just make them single multi line text blocks.

**Comment by jeffchulg** [comment]
Hi,

just because I experienced this many times and even corrected it in FirstResponderKit, keep some splitting in your string concatenations. Otherwise, you could reach a maximum of 4000 chars (see https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2421 )
