### ISSUE TITLE
instruction video seems to be legacy

### ISSUE THREAD

**Issue by bfmcneill** [sqlstudent144/SQL-Server-Scripts#17]
Is the youtube instruction link legacy?

**Comment by sqlstudent144** [comment]
No, it's a joke :)

*Thanks,*


*Kenneth Fisher, Microsoft Data Platform MVP*

*www.sqlstudies.com <http://www.sqlstudies.com>*

**Comment by sqlstudent144** [comment]
The instructional video is as intended.
