### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by ktaranov** [sqlstudent144/SQL-Server-Scripts#3]
Hi, Kenneth. Great thanks for your awesome stored procedures and sql server blogs.

Could you add LICENSE file to your repo? I reccomend MIT license like in my repo https://github.com/ktaranov/sqlserver-kit/blob/master/LICENSE (Brent Ozar also used this type of license - https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/LICENSE.md).

If you choose your license type I can help with adding properly formatted file to your repo via pull request.

**Comment by sqlstudent144** [comment]
Done. And thank you tremendously for your help here.
