### ISSUE TITLE
dbo.sp_DBPermissions.sql third result set ambiguous return order

### ISSUE THREAD

**Issue by ktaranov** [sqlstudent144/SQL-Server-Scripts#5]
From [jzabroski](https://github.com/jzabroski):

I have been at my wit's end trying to understand an issue in production where I'm getting a `SELECT DENIED` error on an `UPDATE` statement, and it works fine in BETA environment.. so I'm using Ken Fisher's wonderful `sp_DBPermissions` to try to compare one by one each permission to see if somehow something got deployed incorrectly.

While doing this, I noticed that it's ordered by grantee_name and object_name but NOT permission_name, leading to situations where `VIEW DEFINITION` and `EXECUTE` permissions on two different servers might be output in different order.

For my use case, I was copy-pasting the output into EXCEL and running a simple =I3=S3 column sanity check operation.

More details here: https://github.com/ktaranov/sqlserver-kit/issues/156

**Comment by jzabroski** [comment]
Thanks, I didn't know these scripts had their own Github.

**Comment by sqlstudent144** [comment]
I'll go ahead and add the permission_name to the order list but also remember that the output is dumped into global temp tables.  If you pass @DropTempTables = 0 then you can query against ##DBPermissions to apply your own order.  You can also pass @Output = 'None' so that the regular output isn't done at all and you just get the data stored in the temp tables.

**Comment by sqlstudent144** [comment]
Added both schema_name (which seemed obvious, not sure why I didn't originally) and permission_name to the order by.

**Comment by jzabroski** [comment]
I guess my use case was to run the sproc with no parameters and use RedGate Toolbelt to dump the SSMS grid to excel.  Yeah, I can do all the stuff you mention, but it's a lot more typing.  Also, I have a general rule that things should "just work" without extra massaging. - If there was a reason NOT to sort by permission_name, then I agree, makes sense to do the long way. 

Anyway, thanks for the wonderful tool.
