### ISSUE TITLE
[sp_SrvPermissions] endpoint & HADR ownership

### ISSUE THREAD

**Issue by Yvesa-G** [sqlstudent144/SQL-Server-Scripts#6]
Using sp_SrvPermissions to clean one instance, I couldn't drop a login which had only CONNECT rights.
It occured that this login still owned one Endpoint and one Availability Group.

It should be very useful to have those ownerships added to sp_SrvPermissions.

Regards,
Yves

**Comment by sqlstudent144** [comment]
sp_SrvPermissions isn't really meant to list out what objects a principal owns.  I am however working on a script that will list out objects that need to be cleaned up (and scripts to do it) before dropping a user/login.

**Comment by Yvesa-G** [comment]
Thanks for your answer
Unexcepted Authorization on objects is a real pain to handle when managing logins
